### ISSUE TITLE
Class icons working incorrectly 

### ISSUE THREAD

**Issue by Zergei** [Macumbafeh/Lorti-UI-Classic3.3.5#1]
the class icons options should for for both Player unitframe and Target Unitframe, but its working only for Target Unitframe who is getting the icons
![image](https://github.com/user-attachments/assets/15b2a4be-8827-46a3-b575-6c0723a3a496)

also it is possible to hide completely the text in the uniframes? because they are showing on mouseover

thanks in advance

**Comment by Macumbafeh** [comment]
Yeah but back in the day someone asked me to be like that 🤷
I can add it on player frame yep

Same thing for the player name also. You want it back?

**Comment by Zergei** [comment]
> Yeah but back in the day someone asked me to be like that 🤷 I can add it on player frame yep
> 
> Same thing for the player name also. You want it back?

yeah i want the class icon in the player unitframe

"Same thing for the player name also. You want it back? "
no ty i want the target name gone if possible and all text in the unitframes like life mana energy etc

**Comment by Macumbafeh** [comment]
> > Yeah but back in the day someone asked me to be like that 🤷 I can add it on player frame yep
> > Same thing for the player name also. You want it back?
> 
> yeah i want the class icon in the player unitframe
> 
> "Same thing for the player name also. You want it back? " no ty i want the target name gone if possible and all text in the unitframes like life mana energy etc

Done ! :)

I need to add FocusFrame to support thickframe now.
![image](https://github.com/user-attachments/assets/1c5cfaf9-9fce-40a9-b159-98b7f8417661)

**Comment by Zergei** [comment]
> > > Yeah but back in the day someone asked me to be like that 🤷 I can add it on player frame yep
> > > Same thing for the player name also. You want it back?
> > 
> > 
> > yeah i want the class icon in the player unitframe
> > "Same thing for the player name also. You want it back? " no ty i want the target name gone if possible and all text in the unitframes like life mana energy etc
> 
> Done ! :)
> 
> I need to add FocusFrame to support thickframe now. ![image](https://private-user-images.githubusercontent.com/47739411/386733688-1c5cfaf9-9fce-40a9-b159-98b7f8417661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MDExMzIsIm5iZiI6MTczMTcwMDgzMiwicGF0aCI6Ii80NzczOTQxMS8zODY3MzM2ODgtMWM1Y2ZhZjktOWZjZS00MGE5LWIxNTktOThiN2Y4NDE3NjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDIwMDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZTVmNGZjMDc2ODE3OGJlOTE4NDcxOWMwMjkxYzQ1YjQxMWY3OTUwYmJhYmNiZjE3MzI5YTVkMjAzNjFiN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NndO8lZC96-ZpL1cw7FgEy-rCCa-C67asdGE8-Jw4HI)

ty for the update hope you can do it for focus frames and all the other frames

**Comment by Macumbafeh** [comment]
It's applied to the focus frame now
